// Generated by https://quicktype.io

export interface Producto {
  id: string;
  createdAt: string;
  updateAt: string;
  nombre: string;
  precio: number;
  existencia: number;
  calificacion: number;
  descuento: number;
}
